/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author squoz
 */
import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;
import fis11_soap.IServer;
import fis11_soap.Result;

public class gui extends javax.swing.JFrame {

    String serverAddress = "";
    IServer soapServer;

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelY = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldX = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldA = new javax.swing.JTextField();
        jButtonSolve = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldServerAddress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FIS11 SOAP");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Вариант.png"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setFocusable(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 276);

        jLabelY.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelY.setText("Y =");
        getContentPane().add(jLabelY);
        jLabelY.setBounds(140, 320, 220, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("X =");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 310, 30, 17);

        jTextFieldX.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldX);
        jTextFieldX.setBounds(40, 300, 90, 32);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("A =");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 340, 30, 17);

        jTextFieldA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldA);
        jTextFieldA.setBounds(40, 330, 90, 32);

        jButtonSolve.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSolve.setText("Решить");
        jButtonSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolveActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSolve);
        jButtonSolve.setBounds(140, 360, 220, 30);

        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonClear.setText("Очистить");
        jButtonClear.setMaximumSize(new java.awt.Dimension(87, 25));
        jButtonClear.setMinimumSize(new java.awt.Dimension(87, 25));
        jButtonClear.setPreferredSize(new java.awt.Dimension(87, 25));
        jButtonClear.setRequestFocusEnabled(false);
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClear);
        jButtonClear.setBounds(370, 360, 220, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("B =");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 370, 30, 17);

        jTextFieldB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldB);
        jTextFieldB.setBounds(40, 360, 90, 32);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Адрес сервера:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 410, 129, 17);

        jTextFieldServerAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldServerAddress.setText("http://localhost:1099/soap");
        getContentPane().add(jTextFieldServerAddress);
        jTextFieldServerAddress.setBounds(140, 400, 450, 32);

        setSize(new java.awt.Dimension(596, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolveActionPerformed
        try {
            String newServerAddress = jTextFieldServerAddress.getText();

            if (!serverAddress.equals(newServerAddress)) {
                serverAddress = newServerAddress;
                JaxWsProxyFactoryBean factoryBean = new JaxWsProxyFactoryBean();
                factoryBean.setServiceClass(IServer.class);
                factoryBean.setAddress(serverAddress);
                soapServer = (IServer) factoryBean.create();
            }

            double x = Double.parseDouble(jTextFieldX.getText());
            double a = Double.parseDouble(jTextFieldA.getText());
            double b = Double.parseDouble(jTextFieldB.getText());

            // Вызов удаленного метода на сервере через web-технологию SOAP
            Result result = soapServer.solve(x, a, b);

            if (result != null) {
                jLabelY.setText("Y = " + result.getY());
            } else {
                jLabelY.setText("ОШИБКА");
            }
        } catch (NumberFormatException e) {
            jLabelY.setText("ОШИБКА");
        }
    }//GEN-LAST:event_jButtonSolveActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTextFieldX.setText("");
        jTextFieldA.setText("");
        jTextFieldB.setText("");
        jLabelY.setText("Y =");
    }//GEN-LAST:event_jButtonClearActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new gui().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonSolve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelY;
    private javax.swing.JTextField jTextFieldA;
    private javax.swing.JTextField jTextFieldB;
    private javax.swing.JTextField jTextFieldServerAddress;
    private javax.swing.JTextField jTextFieldX;
    // End of variables declaration//GEN-END:variables
}
